djangos/api/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
 path('api/hello',views.HelloWorld.as_view(), name='hello'),
 path('api/movies',views.Movies.as_view(), name='movies'),
 path('api/movies/<int:movie_id>',views.Movies.as_view(), name='movies'),
 path('api/review',views.Reviews.as_view(), name='review'),
 path('api/api-token-auth/', obtain_auth_token, name='api_token_auth'),
];

djangos/critical/urls.py
from django.urls import path

from . import views

urlpatterns = [
path('', views.index, name='index'),
path('movie/<int:movie_id>', views.detail, name='detail'),
]

djangos/djangos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('critical.urls')),
    path('', include('api.urls'))
]

djangos/api/models.py
from django.db import models

# Create your models here.

djangos/critical/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
	film_name = models.CharField(max_length=200)
	poster = models.ImageField(upload_to = "critical/static/media")
	release_date = models.DateField()
	classification = models.CharField(max_length=200)
	genre = models.CharField(max_length=400)
	duration = models.TimeField()
	synopsis = models.TextField(max_length=800, null=True)
	def __str__(self):
		return self.film_name

class Review(models.Model):
	movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
	user = models.CharField(max_length=200, default="test")
	stars = models.SmallIntegerField()
	comment = models.TextField(max_length=800)
	def __str__(self):
		return self.comment[0:50] + "..."

djangos/api/views.py
from django.shortcuts import render
from django.core import serializers
from django.db import connection
import json

# Create your views here.
from rest_framework.views import APIView
from rest_framework.response import Response

#Define movies and reviews models
from critical.models import Movie, Review

#Allow just for certain classes
from rest_framework.decorators import authentication_classes, permission_classes
from rest_framework.permissions import AllowAny

@permission_classes((AllowAny, ))
class HelloWorld(APIView):
      def get(self, request):
          return Response({'message','Hello People, Welcome to the movies review api'})
@permission_classes((AllowAny, ))
class Movies(APIView):
      #def post(self,request)
      def get(self, request, movie_id=None):
          if(movie_id!=None):
              cursor = connection.cursor()
              cursor.execute('select m.id, m.film_name, m.release_date, m.classification, m.genre, m.duration, m.synopsis, m.poster,sum(r.stars)*1.0/count(r.id) as rating from critical_movie m left join critical_review r on (m.id=r.movie_id) where m.id='+str(movie_id)+' group by m.id order by m.release_date, rating desc')
              movie = cursor.fetchall()
              cursor.execute('select * from critical_review r where r.movie_id='+str(movie_id));
              reviews = cursor.fetchall();
              return Response({'movie':json.dumps([movie[0],reviews], sort_keys=True, default=str)}, content_type='application/json')
          else:
              cursor = connection.cursor()
              cursor.execute('select m.id, m.film_name, m.release_date, m.classification, m.genre, m.duration, m.synopsis, m.poster,sum(r.stars)*1.0/count(r.id) as rating from critical_movie m left join critical_review r on (m.id=r.movie_id) group by m.id order by m.release_date, rating desc')
              #movies = Movie.objects.raw('select m.*,sum(r.stars)*1.0/count(r.id) as rating from critical_movie m left join critical_review r on (m.id=r.movie_id) group by m.id order by m.release_date, rating desc')
              movies = cursor.fetchall()
              return Response({'movies':json.dumps(movies, sort_keys=True, default=str)}, content_type='application/json')
              #return Response({'movies':serializers.serialize('json',movies)})
class Reviews(APIView):
      def post(self,request):
          req = json.loads(request.body.decode('utf-8'))
          review = Review(movie_id=req['movieid'], stars=req['stars'], comment=req['review'], user='test')
          review.save()
          if(review.id!=None):
             return Response({'message','Your review have been saved successfully.'})
          else:
             return Response({'message','Error. There was a problem saving you review. Try later'})

djangos/critical/views.py
from django.shortcuts import render

# Create your views here.
from .models import Movie, Review

def index(request):
    #movies = Movie.objects.order_by('-release_date')
    movies = Movie.objects.raw('select m.*,sum(r.stars)*1.0/count(r.id) as rating from critical_movie m left join critical_review r on (m.id=r.movie_id) group by m.id order by m.release_date, rating desc')
    context = {'movies': movies}
    #template = loader.get_template('movies/index.html')
    #return HttpResponse(template.render(context, request))
    return render(request, 'movies/index.html', context)

def detail(request,movie_id):
    movie = Movie.objects.get(id=movie_id)
    context = {'movie': movie}
    return render(request, 'movies/detail.html', context)

djangos/critical/templates/movies/detail.html
{% include "./header.html" %}
{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'global/materialize.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'global/style.css' %}">

<div class="row">
 <div class="col offset-s3 s6 offset-s3">
  <h1 class="orange-text">{{ movie.film_name }}</h1>
  <div class="card blue-grey darken-1">
   <div class="card-content white-text">
    <span class="card-title">Synopsis</span>
    <p>{{ movie.synopsis }}</p>
    <br/>
    <h5>Comments</h5>
    {% for review in movie.review_set.all %}
     {{ review.comment }}
    {% endfor %}
   </div>
   <div class="card-action">
    <a href="/">Back</a>
   </div>
  </div>
 </div>
</div>

<script src="{% static 'global/materialize.min.js' %}"></script>
<script src="{% static 'movies/stars.js' %}"></script>

djangos/critical/templates/movies/header.html
  <nav>
    <div class="nav-wrapper black">
      <a href="#" class="brand-logo">Laboratory</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="/">Movies</a></li>
        <li><a href="/admin">Admin</a></li>
      </ul>
    </div>
  </nav>

djangos/critical/templates/movies/index.html
{% include "./header.html" %}
{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'global/materialize.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'global/style.css' %}">
<div class="row">
 <div class="col offset-s3 s6 offset-s3">
 <h1 class="orange-text">List of movies</h1>
 <div class="divider"></div>
 {% for movie in movies %}
  <div class="movie medium card blue-grey darken-1">
   <div class="card-image waves-effect waves-block waves-light">
    <img class="activator" src="static/media/{{movie.poster}}">
   </div>
   <div class="card-content white-text">
	   <span class="card-title activator">{{ movie.film_name }}<i class="material-icons right">. . .</i></span>
   <div class="critical" id="critical-{{ movie.id }}"><canvas id="canvas" width=80 height=20></canvas><span class="rating"></span></div>
    <div class="card-action"><a href="/movie/{{ movie.id }}">GO TO DETAILS</a></div>
   </div>
   <div class="card-reveal">
    <span class="card-title grey-text text-darken-4">{{ movie.film_name }}<i class="material-icons right">X</i></span>
    <p>{{ movie.synopsis|truncatechars:200 }}</p>
   </div>
  </div>
 {% endfor %}
 </div>
</div>

<script src="{% static 'global/materialize.min.js' %}"></script>
<script src="{% static 'movies/stars.js' %}"></script>
<script>
 {% for movie in movies %}
  var starBar{{ movie.id }} = new starsbar('critical-{{ movie.id }}');
  starBar{{ movie.id }}.saved = true;
  starBar{{ movie.id }}.roundStar = false;
  starBar{{ movie.id }}.stars = {{ movie.rating|default_if_none:0 }};
  starBar{{ movie.id }}.selectedBar = ((starBar{{ movie.id }}.stars*80)/5).toFixed(2);
  starBar{{ movie.id }}.canvas.click();
 {% endfor %}
</script>